name: Echo on PR merge to main
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  echo-on-merge:
    # ensure it runs only if the PR was actually merged (not just closed)
    if: ${{ github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Echo merge info
        run: |
          echo "PR #${{ github.event.pull_request.number }} merged into main"
          echo "Title:        ${{ github.event.pull_request.title }}"
          echo "Merged by:    ${{ github.event.pull_request.merged_by.login }}"
          echo "From branch:  ${{ github.event.pull_request.head.ref }}"
          echo "To branch:    ${{ github.event.pull_request.base.ref }}"
          echo "Merge commit: ${{ github.event.pull_request.merge_commit_sha }}"
