name: Echo when terragrunt.hcl reaches main (via PR)

on:
  push:
    branches: [ main ]
    paths:
      - terragrunt.hcl
  workflow_dispatch:

jobs:
  terraform-phases-mimic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
      - run: echo "Terraform init, plan  in Progress"
      - name: Terraform init
      - run: echo "Terraform init,  in Progress"
      - name: Terraform fmt
      - run: echo "Terraform fmt in Progress"
      - name: Terraform Validate
      - run: echo "Terraform validate in Progress"
      - name: Terraform Plan
      - run: echo "Terraform Plan in Progress"
      - name: Terraform Apply
      - run: echo "Terraform Apply in Progress"
