name: Echo on merge to main (terragrunt.hcl)

on:
  push:
    branches: [ main ]
    paths:
      - terragrunt.hcl
  workflow_dispatch:

jobs:
  echo-on-merge-to-main:
    if: >-
      ${{ github.event.head_commit &&
          (startsWith(github.event.head_commit.message, 'Merge pull request') ||
           startsWith(github.event.head_commit.message, 'Merge branch')) &&
          contains(github.event.head_commit.message, 'staging')
      }}
    runs-on: ubuntu-latest
    steps:
      - name: Echo merge info
        run: |
          echo "✅ Merge detected on main with terragrunt.hcl changed"
          echo "Commit: ${{ github.sha }}"
          echo "Actor:  ${{ github.actor }}"
          echo "Msg:    ${{ github.event.head_commit.message }}"
