name: Echo when terragrunt.hcl hits main

on:
  push:
    branches: [ main ]      # shows "main" in Actions UI
    paths:
      - terragrunt.hcl      # only if this file changed
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Echo info
        run: |
          echo "✅ terragrunt.hcl reached main"
          echo "Commit: ${{ github.sha }}"
          echo "Actor:  ${{ github.actor }}"
          echo "Message: ${{ github.event.head_commit.message }}"
