name: Echo on file update

on:
  push:
    branches: [ main ]          
    paths:
      - index.html             

  workflow_dispatch:            

jobs:
  Github-Actions-Trigger-Job:
    runs-on: ubuntu-latest
    steps:
      - name: Show commit info
        run: |
          echo "Github Actions Triggered"
          echo "Ref: $GITHUB_REF"
          echo "SHA: $GITHUB_SHA"
          echo "Actor: $GITHUB_ACTOR"
          echo "Updated by: $GITHUB_EVENT_NAME"
